version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  cms-backend:
    build:
      context: ./CMS_Backend/server  # Correct path for the backend
    container_name: cms-backend
    ports:
      - "3001:3001"
    volumes:
      - ./CMS_Backend/server:/app  # Ensure this maps correctly to your server code
      - /app/node_modules  # This is good to prevent host node_modules from overriding
    environment:
      - NODE_ENV=development  # Ensures it's in development mode

  cms-frontend:
    build:
      context: ./CMS_Frontend/frontend  # Correct path for the frontend
    container_name: cms-frontend
    ports:
      - "3000:80"  # Maps host port 3000 to container port 80
    volumes:
      - ./CMS_Frontend/frontend:/app  # Ensure this maps correctly to your frontend code
    depends_on:
      - cms-backend  # Good to ensure backend starts before frontend

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # Maps host port 80 to container port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Ensure Nginx configuration is correct
      - ./CMS_Frontend/frontend/build:/app/build  # This serves your built files

volumes:
  mongo-data:

