apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cms-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: cms-service-account
    namespace: default
roleRef:
  kind: Role
  name: cms-role
  apiGroup: rbac.authorization.k8s.io

