apiVersion: v1
kind: Service
metadata:
  name: cms-backend
spec:
  selector:
    app: cms-backend
  ports:
    - port: 3001  # Match with your container port
      targetPort: 3001
  type: ClusterIP

