apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cms-frontend
  template:
    metadata:
      labels:
        app: cms-frontend
    spec:
      serviceAccountName: cms-service-account  # Add this line
      containers:
      - name: cms-frontend
        image: ahsan767/cms-frontend:latest  # Replace with your actual frontend image
        ports:
        - containerPort: 80  # Adjust based on your frontend application

